version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: GMT+0
  open-pull-requests-limit: 10
  reviewers:
  - Taimoormk
  assignees:
  - Taimoormk
  labels:
  - upgrade
  ignore:
  - dependency-name: "@react-pakistan/react-icon-collection"
    versions:
    - 3.0.13
    - 3.0.16
    - 3.1.4
    - 3.1.8
    - 3.1.9
  - dependency-name: "@storybook/addon-google-analytics"
    versions:
    - 6.1.20
    - 6.2.7
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.13.15
    - 7.13.9
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@react-pakistan/react-logo-collection"
    versions:
    - 2.0.15
    - 2.0.18
    - 2.1.0
    - 2.1.4
    - 2.1.6
    - 2.1.7
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.20
    - 6.2.2
    - 6.2.7
  - dependency-name: css-loader
    versions:
    - 5.1.1
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: concurrently
    versions:
    - 6.0.1
  - dependency-name: "@storybook/addon-viewport"
    versions:
    - 6.1.18
    - 6.1.21
    - 6.2.7
  - dependency-name: "@react-pakistan/eslint-config-shared"
    versions:
    - 1.2.14
    - 1.2.19
    - 1.2.2
    - 1.2.6
  - dependency-name: "@storybook/addon-controls"
    versions:
    - 6.1.18
    - 6.1.20
    - 6.2.2
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - 6.2.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.13.10
    - 7.13.14
  - dependency-name: styled-components
    versions:
    - 5.2.3
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.17
    - 6.1.20
    - 6.2.2
  - dependency-name: "@storybook/addon-backgrounds"
    versions:
    - 6.1.17
    - 6.1.18
    - 6.2.2
  - dependency-name: chromatic
    versions:
    - 5.6.2
    - 5.7.0
    - 5.7.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: ts-loader
    versions:
    - 8.0.17
    - 8.0.18
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.0
    - 5.27.0
    - 5.28.0
  - dependency-name: "@react-pakistan/util-functions"
    versions:
    - 1.2.14
    - 1.2.15
    - 1.2.17
    - 1.3.2
    - 1.4.7
    - 1.5.1
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.18
    - 6.1.20
    - 6.1.21
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.3
  - dependency-name: react-share
    versions:
    - 4.4.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.17
    - 6.1.18
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: sass-loader
    versions:
    - 11.0.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.13.13
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
    - 5.1.9
