import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '../providers';
import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

interface Props {
  children: ReactNode;
  params: { locale: string; };
}

export const MainLayout: FC<Props> = ({
  params,
  children,
}): JSX.Element => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers locale={params.locale}>
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
};
